### ISSUE TITLE
Delegation issue

### ISSUE THREAD

**Issue by daiangan** [holgern/pynostr#1]
When you try to run the delegation example as in the README file, I always got this error:
```text
TypeError: Object of type bytes is not JSON serializable
```
Apparently, it is on event.py serialize() method when trying to json.dump the data.

I know this is a fork of python-nostr but any help regarding this issue will be appreciated?

**Comment by holgern** [comment]
Pushed a fix,
pynostr will slowly move away from python-nostr and will implement thanks a little bit different.

A added an example how to use delegation to the readme. Let me know if it works. 

I will release a new version with the fix soon.

**Comment by daiangan** [comment]
Thanks, it worked for me.
